name: Ruby

on: [push,pull_request]

env:
  RAILS_ENV: test
  DATABASE_NAME: development
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432

jobs:
  rspec:
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: development_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: install ghostscript and its fonts
      run: |
        sudo apt-get install ghostscript
        sudo apt-get install fonts-noto
    - name: Database Setup
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate
    - name: Run Rspec
      env:
        DATABASE_NAME: development_test
        PRINTIFY_API_TOKEN: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzN2Q0YmQzMDM1ZmUxMWU5YTgwM2FiN2VlYjNjY2M5NyIsImp0aSI6IjAwOTVlYWNlNmZmZWViMTJjYjk4YTk3ZjUzZjU3NTAzZTYzNDA1MzA3MjZiYzQwYTMzMGRjZjAxMjBiY2Y5NmFjZmM4NGJjNjE2NjM1ZmFhIiwiaWF0IjoxNjYwNTk2NDU5LjQ2MDgxNSwibmJmIjoxNjYwNTk2NDU5LjQ2MDgxNywiZXhwIjoxNjkyMTMyNDU5LjQyNzcxNCwic3ViIjoiMTAwNDI4MzgiLCJzY29wZXMiOlsic2hvcHMucmVhZCIsImNhdGFsb2cucmVhZCIsInByb2R1Y3RzLnJlYWQiLCJ1cGxvYWRzLnJlYWQiLCJwcmludF9wcm92aWRlcnMucmVhZCJdfQ.ArYSb8cqCRkeWPL81SSFyIAc4qI4loupnyH-ZuptCSNoOWgrwhWzyqTDXxtOQ6ey4GVoar8HyK4WX-oSH08'
      run: |
        mkdir tmp
        bundle exec rspec spec

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        rubocop_version: gemfile
        reporter: github-pr-check
        level: error
        fail_on_error: true
    - name: Run rubocop
      run: |
        bundle exec rubocop
  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run brakeman
      run: |
        bundle exec brakeman --force
