name: Ruby

on: [push,pull_request]

env:
  DATABASE_NAME: "development"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "postgres"
  DATABASE_HOST: "localhost"
  DATABASE_PORT: "5432"
  RAILS_ENV: test

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run Rspec
      run: |
        bundle exec rspec spec

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run rubocop
      run: |
        bundle exec rubocop
  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run brakeman
      run: |
        bundle exec brakeman --force
